services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${ME_ADMINUSERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${ME_ADMINPASSWORD}
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${ME_AUTH_USERNAME}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${ME_AUTH_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=${ME_SERVER}

# Define named volumes
volumes:
  mongo-data:
    driver: local